#!/bin/bash
#
#
#
echo "Sisestage präegune kellaaeg (tundides)"
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Liiga vara"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Täpselt paras aeg tööd teha"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Telekat vaatama, präegu head filmid"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6]; then
	echo "Käi magama"
else
	echo "Õpi aega tundides sisestama"
fi

