#!/bin/bash
#
#reisi skript vol 2 
#
#algus
#
echo -n "Sisestage reisiate arv: "
read inimesed
echo -n "Sisestage bussi istekohtade arv: "
read istekohad
#
#mitu bussi täidetakse
busside_arv=`expr $inimesed / $istekohad`
#mitu kohta jääb puudu
puudu=`expr $inimesed % $istekohad`
if [ $puudu -eq 0 ]
	then echo "Kokku on vaja $busside_arv bussi"
	else echo "Kokku on vaja `expr $busside_arv + 1` bussi"
fi

#
#lõpp
#
