#!/bin/bash
#
#kasutaja tervitus
#
#skripti algus
who | cut -f1 -d" " | cut -f2 -d "." > eesnimi # lõikame perenimi - see on 2. element peale punkti ja salvestame faili
who | cut -f1 -d" " | cut -f2 -d "." > perenimi # lõikame eesnimi - see on 1. element ennem punkti ja salvestame faili
paste -d"." eesnimi perenimi > nimed #kleebime need failid vastavas järjekorras
cat nimed | sort | uniq # sorteerime väljundi ja võtame korduvad välja
#
#skripti lopp
