#!/bin/bash
echo "Patrick Toms," # kuvab minu nime
echo  "ISP 217"  # kuvab minu õppegrupi järgmisele reale
echo "Antud aine tundub väga huvitav." #kuvab järgmisele reale antud lause
echo "Hetkel tundub aine lihtne ja ma suudan piisavalt kiiresti kaasa teha." # kuvab järgmisele reale antud lause 
# skriptilõpp
